<div class="form_container">
<form action="<?php echo $this->getUrl('*/*/save');?>" method="post">
   
   <div class="field_row row">
      <label for="node_id">Select Category : </label>
      <select name="node_id" id="node_id">
         <option value="cat_1">cat_1</option>
         <option value="cat_2">cat_2</option>
         <option value="cat_3">cat_3</option>
         <option value="cat_4">cat_4</option>
         <option value="cat_5">cat_5</option>
         <option value="cat_6">cat_6</option>
         <option value="cat_7">cat_7</option>
      </select>
   </div>
   
   <div class="field_row row">
      <label for="node_id">NODE_ID: </label>
      <input type="text" name="node_id" id="node_id" class="node_id">
   </div>
   
   
   
   <div class="field_row row">
      <input type="submit" id="node_id" class="node_id button btn" value="Submit">
   </div>
   
   
   
   
</form>

</div>